server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: d209

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false

  cloud:
    aws:
      credentials:
        accessKey: ${AWS_S3_ACCESSKEY}
        secretKey: ${AWS_S3_SECRETKEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    com.board: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: 3600000 #1시간
    refresh: 604800000

#oauth2:
#  # 추후 프론트 서버로 리다이렉트
#  authorizedRedirectUris:
#      -

springdoc:
  swagger-ui:
    tags-sorter: alpha # 알파벳순
    operations-sorter: alpha
  packages-to-scan: com.board.jamesboard
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
